apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memos-ingress
  namespace: memos
  labels:
    name: memos
  annotations:
    spec.ingressClassName: traefik
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - memos
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: svc-app
                port:
                  number: 5230
